### ISSUE TITLE
 Fatal error: Call to a member function menu()

### ISSUE THREAD

**Issue by ghost** [pi-engine/pi#1146]
( ! ) Fatal error: Call to a member function menu() on a non-object in C:\wamp\www\usr\theme\default\template\layout-front.phtml on line 98

Call Stack
#	Time	Memory	Function	Location
1	0.0010	148048	{main}( )	..\index.php:0
2	0.0070	148680	include( 'C:\wamp\www\www\boot.php' )	..\index.php:30
3	0.0810	241072	Pi::boot( )	..\boot.php:29
4	0.1030	270640	Pi\Application\Engine\Standard->run( )	..\Pi.php:294
5	1.5131	2843368	Zend\Mvc\Application->run( )	..\Standard.php:57
6	1.7861	3170600	Pi\Mvc\Application->completeRequest( )	..\Application.php:327
7	1.7861	3170744	Zend\Mvc\Application->completeRequest( )	..\Application.php:156
8	1.7861	3170848	Zend\EventManager\EventManager->trigger( )	..\Application.php:352
9	1.7861	3170920	Zend\EventManager\EventManager->triggerListeners( )	..\EventManager.php:207
10	1.8001	3198584	call_user_func ( )	..\EventManager.php:468
11	1.8001	3198600	Zend\Mvc\View\Http\DefaultRenderingStrategy->render( )	..\EventManager.php:468
12	1.8001	3198728	Zend\View\View->render( )	..\DefaultRenderingStrategy.php:102
13	1.8231	3218072	Zend\View\Renderer\PhpRenderer->render( )	..\View.php:205
14	1.8281	3236184	include( 'C:\wamp\www\usr\theme\default\template\layout-front.phtml' )	..\PhpRenderer.php:506

**Comment by Marc-pi** [comment]
close as inactive
