### ISSUE TITLE
User module Activity

### ISSUE THREAD

**Issue by voltan** [pi-engine/pi#1231]
Need option for add direct link on `Activity` , for example I want have this link ( as route array ) `/shop/panel` or `guide/manage`

**Comment by Marc-pi** [comment]
@voltan it's done?

**Comment by voltan** [comment]
No , But we can work on it on Pi 2.6 , I need more time to think about this

**Comment by Marc-pi** [comment]
does it deal with extending the User Profile left panel with other blocks of menu/submenu, coming from other modules? 
we need indeed this, so user does not get lost between several panels ( a single area to manage everything concerning myself => my latest orders, my favorites, etc.)

**Comment by voltan** [comment]
For this version , we can manage it by template on theme , I still don't now how this part can be finish

**Comment by Marc-pi** [comment]
> For this version , we can manage it by template on theme

yes

>  I still don't now how this part can be finish

i'm sure taiwen will find a way for us to extend the user backoffice (blocks?), with left panels that opens in the same window, like in admin
