### ISSUE TITLE
Add support LiteSpeed

### ISSUE THREAD

**Issue by voltan** [pi-engine/pi#1245]
Hello

itposhible to add support LiteSpeed on setup? I have about 8 websites by pi on LiteSpeed server and I don't have any problem yet , all configs is like apache ,

If needed I can send test host for you

Some websites on LiteSpeed : 
- http://www.payamakyab.com/
- http://www.fantasy.ir/
- http://www.faragostaresh.com/
- http://www.nmgroup.ir/
- http://www.4vade.com/

**Comment by Marc-pi** [comment]
@voltan 
move this to Pi 2.6 milestone is ok?

**Comment by voltan** [comment]
For me is OK
