### ISSUE TITLE
site title  > swap site name and slogan

### ISSUE THREAD

**Issue by Marc-pi** [pi-engine/pi#1253]
hi,

perhaps i am too tired, but where can i reverse the site title value, that is actually composed like thisd

`<title>[site name] - [slogan]</title>`

i just need to have 

`<title>[slogan] - [site name]</title>`

**Comment by Marc-pi** [comment]
````
The policy:
1. If no title is specified, it is rendered as `<slogan> - <sitename>` (homepage)
2. if specified title is provided, it would be rendered as `<specified-title> - <sitename>` (modules)
````

1/ for homepage
we have a regression here since apparently https://github.com/pi-engine/pi/commit/99efa8e79dcca685d5f1aac3e2e935a856b4eb96
=> home page is back to `<slogan> - <sitename>`

2/ for modules, apparently the pattern is `<specified-title> - <modulename> - <sitename>`

I take the opportunity to ask for being able to select the Title Pattern , in my case to be able to NOT to display <sitename> and <modulename> for homepage and modules 
* Those values take space, and in some circumstances give repeated values (in my case, the site url contains a word than i need to put first in Title (for SEO purpose) but not repeat because it is for SE spammy)
* Some will need to keep those 2 value in their sites, other will need only modulename or sitename

can we have a setting somewhere to be able to manage this?

We can image 
SiteName -

**Comment by Marc-pi** [comment]
up !

**Comment by Marc-pi** [comment]
@taiwen , can you check this, to fix the regression and add a new pattern setting somewhere (config files? or system module config)

**Comment by taiwen** [comment]
I think for home page, `<title>[site name] - [slogan]</title>` is the right mode.
For pattern configs, I had ever thought about it, but no good solutions. Do you have any idea?

**Comment by Marc-pi** [comment]
> I think for home page, <title>[site name] - [slogan]</title> is the right mode.

homepage is just in term of SEO a page like another one : one page = one keyword target.
except if you are the CoCa-Cola Company for instance or until your brand is not world famous, you will not use the front page to promote your brand, i.e. user will not search for your company name / site name as keyword.  
example : 
* look at airbnb.com => they do not use airbnb at start
that's because in term of SEO, first words are the most important
==> so we must make it possible to choose the right patern, accordingly to the site context.

> For pattern configs, I had ever thought about it, but no good solutions. Do you have any idea?

the template solution is not the right one, instead we'll need to add custom override on all module templates. => we have to find a solution to give the admin a way to personalize the Title patern
* in case your domain name is long, adding systematicaly the site name in the Title makes the Title value being too long for SEO (max is ~65 characters incl. spaces for web, ~50 for mobile). 
* more important, having an exact match page Title (without site name and module name) is the best effiscient solution for SEO 
* people don't mind the module name or the site name, content must be the king ! but we could image it could be usefull for some admins (ex: if you don't have breacrumb, you need to display the module name so users know where he is).

**Comment by Marc-pi** [comment]
better, but we need to go forward, so can manage the situation listed above

actually, we get this rule for pattern
* if module is not system => `SEO Title - module name - sitename`
postfix == module name - sitename
* if module is system => `SEO Title - sitename`
postfix == sitename
we need a selector within system module config with 
=> need an option to set the postfix pattern through a selector in system module config, with those value
1 light - no postfix (for all modules incl.system)
2 medium - postfix with only sitename
3 full - postfix as actually

and then add a switch/case test un the ThemeAssemble helper

**Comment by Marc-pi** [comment]
@taiwen up ! so we can close this issue. i have to hack the Helper at each install
