### ISSUE TITLE
Comment module > urls are not clickable in comments

### ISSUE THREAD

**Issue by Marc-pi** [pi-engine/pi#1257]
seems filtering is too hard, even for admins : 
- users/admins can not share urls within comments. 
- admin can not add embeded YouTube video through embedded iframes, for instance.

is there a way to improve this?

**Comment by taiwen** [comment]
should be fixed now.

**Comment by Marc-pi** [comment]
* duplicate : fixed,thx
* www.google.com or http://www.google.com : works
* _blank : works
* add url : works for only ONE option (HMTL+JS). normal?
* add iframed video (ex: youtube) : works for ALL options, normal?

**Comment by taiwen** [comment]
`add url : works for only ONE option (HMTL+JS). normal?`
`add iframed video (ex: youtube) : works for ALL options, normal?`

Can you post your test case code?

**Comment by taiwen** [comment]
Branch `markup` is created for further improvements on content compilation and rendering:
https://github.com/pi-engine/pi/tree/markup

**Comment by Marc-pi** [comment]
For URL : simply key in `www.google.com`
FOr VIDEO : `<iframe width="560" height="315" src="//www.youtube.com/embed/DVwHCGAr_OE" frameborder="0" allowfullscreen></iframe>`

Beware : i had first strange behavior after changing each content format option in module's config, the clickable url came after few minutes. to be sure, i used this protocol to prevent from any cache : 
* change the option + submit
* update all modules to clear cache from System > Manage Module Tab
* force browser cache with F5

**Comment by Marc-pi** [comment]
@taiwen 
I made new tests based on r4507

* add video works on html and markdown, not on plain text => seems attended behavior
* add url (www.google.com) works on plaintext(!), not on markdown and html, normal?

**Comment by Marc-pi** [comment]
additionally to my previous findings, please add `rel=nofollow` in <a> link to prevent from Spam

**Comment by sta2m** [comment]
> add rel=nofollow in <a> links (on external links only)

Fait.

> l'autre solution peut être plus simple est de ne pas ajouter le nofollow sur commentaires postés par l'admin ou webmasters

J'ai tenté en vain de passer des options à ce filtre. J'ai galéré et j'ai décidé d'abandonné car trop chronophage. A voir avec Taiwen éventuellement, ou sinon, tu me donnes ton go pour creuser encore, mais gaffe ;)

**Comment by Marc-pi** [comment]
heu, ce linkyfy est utilisé seulement dans les commentaires ou partout?
car sinon tout mes liens internes, notamment ceux dans les contenus, seront no-follow, et donc cela n'est pas bon.

voilà pourquoi je parlais en gras des liens externes

quid de ma solution avec trust domain?

**Comment by sta2m** [comment]
> heu, ce linkyfy est utilisé seulement dans les commentaires ou partout?

Pour moi, uniquement dans les commentaires. 

> le mieux serait d'avoir une liste de trust domain non soumis à cette règle, avec par défaut le domaine du site (ex: ca me permettrait d'ajouter brianconnais/serre-poncon)

J'étais resté sur l'autre solution plus simple, qui en fait ne l'était pas vu que nécessitait de pouvoir passer une config au filter. Le trust domain ne devrait pas être trop compliqué à mettre en place. 
Je te le mets en place du coup ?

**Comment by Marc-pi** [comment]
> Pour moi, uniquement dans les commentaires.

ca veut dire que tu as vérifié ou que c'est une supposition?

> Je te le mets en place du coup ?

ben oui, si tu trouves pas plus simple. Je veux juste pour garder le jus pour mes propres liens (site EDQ mais aussi EDSP/EDB, ADS), mais pas pour les commentaires laissés par les membres du site.

Q1 : le filter est appliqué à chaque loading du contenu ou à chaque post du formulaire?

Q2 : qui de ma question sur la lib?

**Comment by sta2m** [comment]
> ca veut dire que tu as vérifié ou que c'est une supposition?

J'avais fait une recherche du filtre qui n'apparaissait que pour les commentaires.

> ben oui, si tu trouves pas plus simple. Je veux juste pour garder le jus pour mes propres liens (site EDQ mais aussi EDSP/EDB, ADS), mais pas pour les commentaires laissés par les membres du site.

Ok, je fais ça demain. 

> Q1 : le filter est appliqué à chaque loading du contenu ou à chaque post du formulaire?

Chaque loading de chaque commentaire

> Q2 : qui de ma question sur la lib?

Il n'a pas utilisé de lib pour ces filtres là. La seule lib qu'il a du utiliser, c'est MarkdownDocument pour Markdown je pense et elle est manquante ;)

**Comment by sta2m** [comment]
> trust domain

Fait. Mettre à jour core et module comment. Paramétrer les domaine dans la config de comment.

**Comment by Marc-pi** [comment]
now you can declare trust domain in config - those links in comment post use dofollow, other links in comment post will use nofollow

**Comment by sta2m** [comment]
update pour correction d'un notice.
