### ISSUE TITLE
global check / default Pi install > SEO issues

### ISSUE THREAD

**Issue by Marc-pi** [pi-engine/pi#1282]
> It is always good to see how crawlers see our sites. i've made a test with default PI Install

Results are here http://seorch.eu/seo-check-scanner/mdxprod-com-2014-11-08-10-90-48.html

**What we need to fix**

* missing H2 tag in comment and article modules

* duplicate meta description in comment / article / search modules
    * we need to add a field in module config to personalize Index Page Description/Title for those modules

* missing/empty alt tag in article and comment modules

* some links missing on article module (media)

* missing meta description in article

* strange links generated by comment module > perhaps it is due to the url within comment we are working on `http://mdxprod.com/pi-engine/www/comment/list/%3Ca%20href=`

* strange nested redirection for login : how it is possible to have such loops?

`http://mdxprod.com/pi-engine/www/user/login/?redirect=/pi-engine/www/user/login/?redirect%3D/pi-engine/www/user/login/?redirect%253D/pi-engine/www/user/login/?redirect%25253D/pi-engine/www/user/login/?redirect%2525253D/pi-engine/www/`

there are also links with even more nested iterations

`http://mdxprod.com/pi-engine/www/user/login/?redirect=/pi-engine/www/user/login/?redirect%3D/pi-engine/www/user/login/?redirect%253D/pi-engine/www/user/login/?redirect%25253D/pi-engine/www/user/login/?redirect%2525253D/pi-engine/www/user/login/?redirect%252525253D/pi-engine/www/user/login/?redirect%25252525253D/pi-engine/www/user/login/?redirect%2525252525253D/pi-engine/www/user/login/?redirect%252525252525253D/pi-engine/www/`

**Comment by voltan** [comment]
On theme , just h1 for homepage needed? perhaps if we have any control for check `isHomepage` can help us

**Comment by Marc-pi** [comment]
> On theme , just h1 for homepage needed? 

see https://github.com/pi-engine/pi/issues/1285.
"perhaps if we have any control for check isHomepage can help us" : why not adding a config value for H1 homepage, aside website Title

> Other Theme/Template main issues to fix 

* duplicate meta description in comment / article / search modules
  * need to add some dedicated configs on those modules
* i need to recheck globally Hn after the H1 for homepage is fixed
     * missing H2 tag in comment and article modules
     * missing/empty alt tag in article and comment modules
     * some links missing on article module (media)
     * missing meta description in article

> For Taiwen

* infinite redirection loops
* strange links generated by comment module

**Comment by voltan** [comment]
> duplicate meta description in comment / article / search modules 

Its not theme edit

> i need to recheck globally Hn after the H1 for homepage is fixed  

Its not theme edit too , I will update comment and profile modules 

> "perhaps if we have any control for check isHomepage can help us" : why not adding a config value for H1 homepage, aside website Title

each website have different strategy , I am not agree by config, just for homepage we can have H1 as website title , on other themes and websites , designers need change it if any customize needed

**Comment by taiwen** [comment]
> duplicate meta description in comment / article / search modules

What is this?

**Comment by Marc-pi** [comment]
> duplicate meta description in comment / article / search modules

those 3 modules make use of the Site meta description (from System module), so it is seen as poor quality by search engines, and more to say seen as duplicate content. 
Like book's chapters, module must have their own Title/Keyword/Description, those are not the system module, but they have their own content. 
=> On other modules, we set those values in module configs, those are dedicated to the module. this helps also to build a strong semantic ecosystem about the site's content (good for SEO).

NB : usually, search feature in a website is seen as a utility, we could set its content it as no-index/no-follow for all pages, because it generates content that comes from the other modules, so it is also duplicate content in a way. 

> Where did you get the login loops? I couldn't find with seorch.eu

have a look at the 2 examples given in my first post.
i've generated a new analysis, look for instance at "URLs with more than 115 characters"
http://seorch.eu/seo-check-scanner/mdxprod-com-2015-01-05-07-81-97.html
it is also seen by google in GWT, but the looping is a bad quality factor. see the solution i thought about above, but perhaps you can find a better way

**Comment by taiwen** [comment]
> duplicate meta description in comment / article / search modules
So, what you suggest is to set specific head description for each module.

**Comment by Marc-pi** [comment]
yes, have a look at what hossein made in his modules : 
* a default SEO Title/Keyword/Description for any empty page within the module, per module logic.
* Due to competition, crawlers are being nowadays more and more qualitative => user centric, 
* but finally those are only w3c html rules about the correct purpose of those semantic containers :-)

**Comment by Marc-pi** [comment]
> For Taiwen

* infinite redirection loops : fixed , GREAT, thanks

> On theme / Voltan

* see https://github.com/pi-engine/pi/issues/1285.
* missing H1 for front page => "perhaps if we have any control for check isHomepage can help us"
* missing H1 for comment and article modules

Then we will make another recheck globally Hn after those are fixed

> Duplicate or empty meta

* duplicate meta description in comment / article / search modules
  * need to add some dedicated configs on those modules
* duplicate meta description /user/login/ and system/user/profile
* empty meta description in yoursite.com/article/media/download/id-14

**Comment by voltan** [comment]
just one point, it possible to have function `isHomepage` for detacte system module index page ( homepage ) as helper , than we can use it on themes . and have meta description on theme as `$description` for use on head part , for example dublic core

**Comment by taiwen** [comment]
What do you do with `isHomepage`?
Can you add what you need to `usr/module/system/template/font/system-home.phtml`? It is dedicated to system homepage.

**Comment by Marc-pi** [comment]
@taiwen about https://github.com/pi-engine/pi/commit/d6edfe868945bde1befe0fd069e03993e2cb485a 
actually you added author, keyword, generator, description
nice, but 
* we need Title, that is the most important for SEO !
* i think author and generator are not needed

@voltan don't forget taiwen's question !-;)

**Comment by voltan** [comment]
I wanted use it on theme files , at this moment just for h1 tag, But I see when we install user module. system module just have website index on front, than I can use ` if ($module == 'system') ` for manage index. no any extar option needed

I will update theme and templates

**Comment by Marc-pi** [comment]
@voltan thanks (ok for H1 on front page, it is up to the dev to put it elsewhere from on logo)
@linzongshu 
. only H1 on article is missing now
. you can also add sitemap to Article https://github.com/pi-engine/pi/issues/1235
@taiwen , can you bump the article to linzongshu dev so we close article issues

**Comment by Marc-pi** [comment]
additionally, user Profile page's Title is not unique : all users have same profile SEO Title 
=> we need to personalize it with display name (even if by default we will restrict access to the page : admin can decide to bring it public through permissions).

**Comment by Marc-pi** [comment]
@voltan can you check the template SEO issues so we can close this ?

**Comment by voltan** [comment]
I can work on comment and user templates. any other module needed?

**Comment by Marc-pi** [comment]
See my last 2 posts in this issue, I checked intensively and have reported all issues.

**Comment by voltan** [comment]
Meta author and Meat generator removed , add on theme manually ?

**Comment by Marc-pi** [comment]
@voltan , good, just you forgot https://www.com/comment/post/2

**Comment by voltan** [comment]
OK , Added https://github.com/pi-engine/pi/pull/1338 , I think we can close this
