### ISSUE TITLE
Improve h tags for SEO

### ISSUE THREAD

**Issue by voltan** [pi-engine/pi#1285]
As here : https://github.com/pi-engine/Marc-Voltan/issues/186

What is your idea about update themes and all module templates and manage h tags ?

We need to do : 
* Replace h1 on theme to h2 ( just for system module keep h1 )
* On all templates on all modules add page title by h1 tag 
* Manage other titles and important texts by h2 to h6

**Comment by Marc-pi** [comment]
on default theme, some issues
* remove H2 for site logo/name, must not be Hn, but simple css class
* add `H1 for front page` either directly in front template, either through system module configs (far far better)
   * please note that H1 must be different from front page Title value also
* adjust dublin core `dc:description` and `dc:subject`
    * `dc:description` : must be populated by `description` value, not `site slogan - site name`
    * `dc:subject` : can be populated by `front page H1` if we set it as system module config

```
<meta name="author" content="Pi Engine">
<meta name="generator" content="Pi Engine">
<meta name="keywords" content="Pi Engine,Web application,PHP,Zend Framework">
<meta name="description" content="Pi Engine is an extensible development engine for web and mobile applications written in PHP.">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta property="dc:title" content="Pi Engine" lang="fr">
<meta property="dc:subject" content="Propulse vos applications web et mobiles" lang="fr">
<meta property="dc:description" content="Pi Engine - Propulse vos applications web et mobiles" lang="fr">
<meta property="dc:type" content="text">
<meta property="dc:publisher" content="Pi Engine">
<meta property="dc:language" content="fr">
```

**Comment by Marc-pi** [comment]
made there https://github.com/pi-engine/pi/pull/1313
