### ISSUE TITLE
update to zf 2.3.5 (with sec fix)

### ISSUE THREAD

**Issue by Marc-pi** [pi-engine/pi#1309]

**Comment by Marc-pi** [comment]
@taiwen don't forget that one, so we can test (even if sec is also fixed in uptocome 2.3.5)

**Comment by voltan** [comment]
I vote to keep it for next version, not very important for now , and if any part changed we need update all modules and core codes

**Comment by Marc-pi** [comment]
I would like first to know if the session sec fix has any impact on our websites before taging it for next version. Can you confirm?

**Comment by Marc-pi** [comment]
@taiwen, 2.3.5 is out

**Comment by Marc-pi** [comment]
2.4 is planned for mid march

**Comment by Marc-pi** [comment]
2.3.6 is out with another sec fix (csrf) @taiwen »» plz upgrade so we patch our sites

**Comment by Marc-pi** [comment]
2.4 is out !!! @taiwen

**Comment by Marc-pi** [comment]
2.4.1 is about to be released @ taiwen

**Comment by Marc-pi** [comment]
@taiwen 2.4.8 is out ! please let us know when you're back, we need upgrades
