### ISSUE TITLE
var/config/engine.php vs custom

### ISSUE THREAD

**Issue by Marc-pi** [pi-engine/pi#1311]
@taiwen 
When changing the environment in config/engine.php, seems it does not override the one from custom.
So what is the custom file for? seems it is to protect the config/engine.php when upgrading, right?

so i guess i can update the upgrade instruction here https://github.com/Marc-pi/Pi-HowTo/wiki/2-Pi-Install-Upgrade-Run-SSL, can you have a look ?

NB : would be nice to activate back the environment setting from system module configs

**Comment by taiwen** [comment]
configs in `custom/` have higher priority than in `config/`

**Comment by Marc-pi** [comment]
so in case of upgrade, we can write on var/config/engine.php ?

**Comment by Marc-pi** [comment]
please have a look at our upgrade checklist and tell us if some changes needed
