### ISSUE TITLE
Roxyfileman for CKEditor

### ISSUE THREAD

**Issue by voltan** [pi-engine/pi#1314]
What is your idea to add http://www.roxyfileman.com as file / image manager for CKEditor ? on my test it work good , But some settings needed

**Comment by Marc-pi** [comment]
Better than ckfinder ?

**Comment by voltan** [comment]
ckfinder not free , have limited time demo licence and 99 USD for each year http://cksource.com/ckfinder/buy

**Comment by taiwen** [comment]
Can you integrate it?

**Comment by voltan** [comment]
yes , I install it on fantasy.ir ( pi 2.4 ) , Just I need try to add setting for paths . I will work on it and send pull request

**Comment by Marc-pi** [comment]
looks very similar to CKFinder, crazy

**Comment by voltan** [comment]
I send pull request, just at this moment upload path set on `www/script/editor/fileman/Uploads/` and I can't change the path, before use we need set upload path on www/upload/fileman

**Comment by Marc-pi** [comment]
@voltan ,
did you have a look at this official optional plugin ?
http://ckeditor.com/addon/image2 <=> http://sdk.ckeditor.com/samples/captionedimage.html

**Comment by voltan** [comment]
We need option for upload image , this is good plugin but don't have upload image option

**Comment by Marc-pi** [comment]
Yes, was just to let you know in case you missed it (for other projects).

**Comment by voltan** [comment]
Keep it for next version too , perhaps if we have general media module is better. more think needed
