### ISSUE TITLE
update to bootstrap 3.3.4

### ISSUE THREAD

**Issue by Marc-pi** [pi-engine/pi#1317]
http://blog.getbootstrap.com/2015/01/19/bootstrap-3-3-2-released/

**Comment by voltan** [comment]
We have version 3.3.1 , can you please send pull request for new version ? I think we can keep it for next version too.

**Comment by Marc-pi** [comment]
yes, i would like, but first i need to know why we need to retrieve glyficons from standard package, because actually it generates 404 errors (for few months, bing and google crawlers are seing js like html pages) => we get a penaly with our implementation
@taiwen , it there a way to manage this better ? 

Bing 
````
https://www.mysite.com/public/vendor/bootstrap/fonts/glyphicons-halflings-regular.eot?

generates such a message

The link to 'https://www.mysite.com/public/vendor/bootstrap/fonts/glyphicons-halflings-regular.eot?' has resulted in an error. 
Details: 404 Not Found

````

**Comment by Marc-pi** [comment]
@taiwen seems you used a customized package http://getbootstrap.com/customize/ (i saw the config.json) and that you uncheck the glyfycons and the 3 Iconography fields values, right?
strange in that case we have such an error as explained above
3.3.4 is out, please confirm so i can update !

**Comment by Marc-pi** [comment]
for further reference
* http://stackoverflow.com/questions/22029116/bootstrap-3-without-glyphicons-replaced-with-font-awesome
* http://stackoverflow.com/questions/27745069/replace-glyphicons-with-font-awesome-in-css-using-less-and-grunt
