### ISSUE TITLE
Leverage CKEditor Pi Integration

### ISSUE THREAD

**Issue by Marc-pi** [pi-engine/pi#1320]
I spend some time at understanding better CKEditor features, so we all better know how to use it at its best well integrated into Pi. We all have to write down content, and we have to ease text formatting, especially with Hn and CSS style, to bring users output/UI consistency and keep text well integrated within the site's theme design.

> The goal of this issue is to make a sum up for later usage, especially after any Pi upgrade.
> There are some CKEditors settings to use to leverage the Editor's usage in PI Context.

**CKEditor location in Pi**
CKEditor is actually located in \www\script\editor\ckeditor

from http://docs.ckeditor.com/#!/guide/dev_configuration
CKEditor custom settings can be set in 3 ways : 
- In-Page Configuration
- config.js file (at the root) : no advised ;-)
- Custom Configuration File 

NB there are precedence rules http://docs.ckeditor.com/#!/guide/dev_configuration-section-configuration-loading-order between the 3 ways

**Best Practices**
http://docs.ckeditor.com/#!/guide/dev_best_practices
- **don't be afraid of custom build with CKBuilder**  (to remove plugins or buttons in your configuration and not have a full package)
  remove plugins or buttons in your configuration
- **use minified version**
-  **protect config files** (config.js, contents.css, styles.js and custom template files)
  => i vote for theme folder, since we need to define styles or use theme styles
- **Configure content filtering (ACF Advanced Content Filter)**
  ex : `<iframe>` and `<style>` elements are disable by default.
  Automatic mode is enabled by default.We'd better to set Automatic mode and allow additional tags/properties
  => see http://docs.ckeditor.com/#!/guide/dev_acf
  CKEditor will only accept content that was defined as allowed by enabled CKEditor features (such as plugins or buttons). 
  http://sdk.ckeditor.com/samples/acf.html
- **Configure Styles drop-down (styles.js and contents.css)**
  http://docs.ckeditor.com/#!/guide/dev_styles
  By default there is a generic Styles drop-down with default styles. 
  http://sdk.ckeditor.com/samples/styles.html
  The entries available in the drop-down list must be customized to suit our needs.
  => Using an External Styles Definition styles.js File  we can place anywhere 
  http://sdk.ckeditor.com/samples/classic.html

NB Another method of customizing the styles and populating the drop-down list is to use style definitions coming from an external existing CSS stylesheet file , through  the optional Stylesheet Parser plugin but the Stylesheet Parser plugin is incompatible with Advanced Content Filter, so it disables the filter after installing. 
- **Configure format**
  The text format feature is automatically integrated with Advanced Content Filter, so all custom format definitions are treated as allowed by the editor content filtering mechanism. 
  http://docs.ckeditor.com/#!/guide/dev_format

**Other customizations that could be usefull**
- **modify toolbar if needed**
  use the  toolbar utility available in the disto to config the needed buttons and groups then get source code to add to editor configuration
  http://docs.ckeditor.com/#!/guide/dev_toolbar
  http://sdk.ckeditor.com/samples/toolbar.html
  When content filtering is working in automatic mode, toolbar configuration affects what is allowed in the editor. In other words, CKEditor will only allow the type of content that can be created using the available toolbar buttons and will remove disallowed elements. 
- **modify editor UI Color**
  http://docs.ckeditor.com/#!/guide/dev_uicolorpicker
- **text and background color**
  you need the color button plugin for that purpose (but not advised)
  your can set a custom color list. but it's better to use style drop down definition.
  http://docs.ckeditor.com/#!/guide/dev_colorbutton
- **add text formatting removal button**
  there is a plugin for that 
  http://docs.ckeditor.com/#!/guide/dev_removeformat
- **Using Native Browser Spell Checker**
  By default, browser spell check functionality is disabled
  http://sdk.ckeditor.com/samples/spellchecker.html

Other interesting samples: http://sdk.ckeditor.com/index.html

**Comment by Marc-pi** [comment]
@taiwen 

> Can we set a /custom dir somewhere so we manage well our settings?

i did not see such a way in the actual integration, or i missed something?

**Comment by voltan** [comment]
we can use this plugin for upload image by user http://ckeditor.com/addon/simpleuploads
just if we can set upload path easy
