### ISSUE TITLE
Profile > Access denied page issue

### ISSUE THREAD

**Issue by Marc-pi** [pi-engine/pi#1322]
* With  default theme > If you do not authorize guests to gain access to Profile, you get a blank page instead of a "Access Denied" page
* additionally, can we change the Access Denied Page so the message is displayed within the theme, instead of such an hugly "technical" page out from theme => flashMessenger technically associated to the right Forbidden 401 error code message would be far far better !!!

![accessdenied](https://cloud.githubusercontent.com/assets/919332/5883883/bdc8ce20-a356-11e4-84e6-796ce725db75.JPG)

**Comment by Marc-pi** [comment]
good
just if you can improve so 
* the red background is not sticked to the theme top bar, would be fine. must look more like flashmessenger message so the "block" is not sticked to menu bar
* "You are not allowed to access the page. Please come back later." ==>  You are not allowed to access the page. Return Home" with clickable link to site homepage
@voltan if you can see other improvements, let us know

**Comment by voltan** [comment]
After add 
```
$this->controller && 'login' != $this->controller
```
Admin side not available for login

**Comment by Marc-pi** [comment]
confirmed, admin side not available for admin in  usr/theme/default/template/error-denied.phtml
see https://github.com/pi-engine/pi/commit/acd2fd73ef9e8e012a45f355076525f6802cb2ea

**Comment by Marc-pi** [comment]
fixed
