### ISSUE TITLE
Page & Utiliy modules > add selector to manage page proper indexing (meta robots)

### ISSUE THREAD

**Issue by Marc-pi** [pi-engine/pi#1323]
Page module is mostly used to manage Corporate Pages (About Us, Privacy, etc.).
- Those page are usually not dedicated to the site's purpose e.g. site content
- that's why the Page Module does not appear in Menus and it does not have an index page.
-  => page items have generally a poor interest for users e.g. for engines, admin make use of content oriented modules instead (Article, News, etc..)

Can we add a selector in the page Form (so each Page Module item can have its own setting) to manage well the way those accessory pages are indexed, with those values 
- fully indexed equiv `<META NAME="robots" CONTENT="index,follow">` or without any robots tag
- noindex, nofollow equiv `<META NAME="robots" CONTENT="noindex,follow">`
- index, nofollow `<META NAME="robots" CONTENT="index,nofollow">`
- noindex, nofollow `<META NAME="robots" CONTENT="noindex,nofollow">`

> do we need such a meta for others site pages?

well, i don't thing we need this in all modules item forms.  Add this to page is sufficient IMHO
i don't know if those tags are awaited by crawlers,we've to check. But for sure adding a method so that a dev can use it in his modules is a necessity.

By this way, crawlers will focus on the other most important contents and we will able to 'hide' sensitive data if needed.

**Comment by Marc-pi** [comment]
i vote to add noindex, nofollow on login and redirect pages

**Comment by taiwen** [comment]
For `search` and `comment` I think it should be `index,follow`, right?

**Comment by voltan** [comment]
I think so , on search we have direct links and it good if cached by google

**Comment by Marc-pi** [comment]
> For search and comment I think it should be index,follow, right?

* Comment module > it depends : to limit duplicate content it is often strongly advised to concentrate the link juice on items.
* Search > on index yes, but on search results it is not advised at all to not have duplicate content in case a user link outside the search url with search query value. Apparently, the search index and search result page are the same page (single template).

> on search we have direct links and it good if cached by google

we have already RSS, sitemap, and other pages. it is already duplicate content. we'd better to concentrate the link juice.

**Comment by voltan** [comment]
I vote to move this issues for next version . we can do many things , but test needed and ath this moment I think we don't have time to work on new features
