### ISSUE TITLE
Asset > missing index.html

### ISSUE THREAD

**Issue by Marc-pi** [pi-engine/pi#1325]
- Can we add index.html files automatically in /asset subdirecties created for modules & themes ?
- We have also this need to /upload directories created by modules to store for instance uploaded content
- we have also this in some other directories (public/vendor/bootstrap/subdire, etc.static/vendor/backbone) => perhaps if we have a script that creates automatically missing index.html file in case there are none or no index.php file would be fine.

NB : during that time, don't forget to add in your .htaccess `Options -Indexes` to prevent from directory blind traversal => perhaps adding this in the default .htaccess would be a better measure.

**Comment by voltan** [comment]
> Can we add index.html files automatically in /asset subdirecties created for modules & themes ?

If add index on theme and module asset folder , it will move on to main asset folder

But for other folders we can close them by htaccess ,
