### ISSUE TITLE
search > page module results are not well rendering ( latin characters )

### ISSUE THREAD

**Issue by Marc-pi** [pi-engine/pi#1326]
https://www.yoursite.com/search/?q=queyras

éàè etc. are not displayed like results for other modules

**Comment by voltan** [comment]
I see same problem on Persian. I think its urlencode problem. I will fix it

**Comment by voltan** [comment]
can you please make example for me , I see it work fine

**Comment by Marc-pi** [comment]
see the link i posted above
rendering is for instance
`Mentions Legales Publication - Edition - R&eacute;alisation - H&eacute;bergement &nbsp; Publication-Edition-R&eacute;alisation Envie de Queyras SARL (en constitution) La Lauzi&egrave;re 05460 RISTOLAS France. &nbsp; H&eacute;bergement `

**Comment by voltan** [comment]
Can you please resubmit pages ? I try submit your text on local host and it save like `Publication - Edition - Réalisation - Hébergement` , But on your website and page module. its save or render as `Publication - Edition - R&eacute;alisation - H&eacute;bergement` on page surece,

perhaps it was old version editor problem

**Comment by Marc-pi** [comment]
no, that did not the trick, i still have the issue

**Comment by Marc-pi** [comment]
@voltan, did you have a look?

**Comment by voltan** [comment]
On my test it work fine . can you please send test text here? I see texts save in your DB as `H&eacute;bergement &nbsp;`, perhaps by update texts it solve

Your DB is utf-8 ?

**Comment by Marc-pi** [comment]
Yes, it is. I will test in few hours by sending again clean text.
