### ISSUE TITLE
search > google and baidu links

### ISSUE THREAD

**Issue by Marc-pi** [pi-engine/pi#1327]
![search](https://cloud.githubusercontent.com/assets/919332/5973361/a03415a2-a867-11e4-8618-acdd0b463844.JPG)

can we add an option to hide google and/or baidu links in template in module config?
we can imagine also the possibility to add Band/or local search engine also.

**Comment by voltan** [comment]
We can work on it on next version too. at now we can edit and use custom template

**Comment by Marc-pi** [comment]
we made on search 1.2.3
