### ISSUE TITLE
pi waffle cards

### ISSUE THREAD

**Issue by Marc-pi** [pi-engine/pi#1332]
https://github.com/blog/1930-task-lists-are-open-source

![waffle](https://cloud.githubusercontent.com/assets/919332/5984726/642c2ad2-a8d9-11e4-8ed7-8d2251d6740b.JPG)

**Comment by taiwen** [comment]
Nice tool

**Comment by Marc-pi** [comment]
nice, but doubt that it is really usefull, except for the project manager
