### ISSUE TITLE
Pi meta description > residual too short values on core

### ISSUE THREAD

**Issue by Marc-pi** [pi-engine/pi#1339]
we made a good job, Pi is quite clean now with meta and other SEO messages on GWT/BWT.
==> The only values we need to tackle now deal with too short meta description values on :
- /user/profile/1‎ => we can imagine such a value " To know more about `<username>` profile : his bio, websites and social networks, and his activity on the website"
-  ‎/user/login/‎ => we can imagine such a value "Use this page to connect to our website and participate, share contents, use our features, and interacts with other members"
- /comment/post/1‎ => we can imagine have such a comment with a concatenation " Read the comments added on the `<item name)` , add your own opinions/advises , and interacts with others".

Some improvement to reduce duplicate content : 
- /comment/post/1‎ => can we improve the comment SEO Title, to put the itemname also in Title? => "Comment post `<nr>` on `<item SEO TItle>`
- guide/item/lacs-lacroix-lacs-de-segure => can we change All Comments (1) [Tous les Commentaires(1)] to "All Comments on `item SEO Title` (1)", to bring unicity on comments accross the different items.

And one on modules (i did not test on Article, that has a lot to do on the meta)
- /news/topic/list‎

**Comment by voltan** [comment]
At this moment core is more important, is this texts is OK , I can set and pull request , for comments , on which page ? can you please send example link here?

**Comment by Marc-pi** [comment]
* for example link, add EDQ as base url on the above paths to see
* i've added the suggested Title for comment

**Comment by Marc-pi** [comment]
* extra `print_r($target);` to remove in usr/module/comment/src/Controller/Front/PostController.php
, i guess
* you forgot to improve /comment/post/1‎ SEO Description 
*  about this one ==> guide/item/lacs-lacroix-lacs-de-segure => can we change All Comments (1) [Tous les Commentaires(1)] to "All Comments on `item SEO Title` (1)", to bring unicity on comments accross the different items. ==> is it added in module template or added by core?
* about this one /comment/index/load/‎ => no title => i don't think we fix this one yet

**Comment by voltan** [comment]
> extra print_r($target); to remove in usr/module/comment/src/Controller/Front/PostController.php , i guess

Fixed

> you forgot to improve /comment/post/1‎ SEO Description 

I add better title and use that for SEO Description , SEO Description  need be between 80 to 160 Characters and whit ` Read the comments added on the  ((item name)) , add your own opinions/advises , and interacts with others` it more than 160

> about this one ==> guide/item/lacs-lacroix-lacs-de-segure => can we change All Comments (1) 

Title not available here , 

> about this one /comment/index/load/‎ => no title => i don't think we fix this one yet

did you see this page? its json output for load comment : https://www.envie-de-queyras.com/comment/index/load

**Comment by Marc-pi** [comment]
* I add better title and use that for SEO Description : hum, that's not a Description that incitates user to click. We'd better to have a dedicated value, different from Title. Lengh here is not so important, you can reduce to `Read the comments added on the ((item name)) and interacts with others`
* guide/item/lacs-lacroix-lacs-de-segure : Title not available here => ? it is available in comment/index page, what do you mean
*about this one /comment/index/load/‎ => no title =>its json output for load comment ==> yes, we have an issue on this. We'll need to be carefull, angular and backbone are not SEO friendly at all. there are turnaround available, but in our case, we have to find a way so we don't have such an invalid path available in code.

**Comment by Marc-pi** [comment]
about ajax, https://developers.google.com/webmasters/ajax-crawling/

**Comment by Marc-pi** [comment]
@voltan , can you add the dedicated text i proposed, that's not good to have the same value
