### ISSUE TITLE
Default Pi Editor loading issue

### ISSUE THREAD

**Issue by Marc-pi** [pi-engine/pi#1342]
I was not able to find why default editor is not loading anymore Ckeditor on my webiste that runs latest pi code r 4547:
- i have to force using CKEditor in System Module Configs to make it display in textareas
- it occured recently with the latest commits afer r4521 (i did not have the issue with r4521), but during that time i added content also

So i made those tests :
- on a fresh install with latest r4547, no issue, even when running the same version of non core modules (news, contact, etc.)
- i checked my latest other changes, the only recent was the CKFinder deletion. So i installed it back, thinking perhaps CKFinder has a dependency upon CKEditor, but did not change the issue. CKEditor was not loaded when Use Default PI Editor was set in System module config.
- no message in debug : Editor Service is loaded correctly

My site was upgraded to latest pi code, so i guess it is either :
- a content issue that breaks somewhere (escaper missing in Editor loading?), but i have the issue also when trying to add a new content (in Page or News or Widget)
- an upgrade process issue around var/config files, but i was not able to find the issue (check the config files we are not upgrading https://github.com/Marc-pi/Pi-HowTo/wiki/2-Pi-Install-Upgrade-Run-SSL)

@voltan do you have such an issue too?
@taiwen , can you help me pointing out the culprit?

**Comment by voltan** [comment]
On system module config , if you set default editor to CKEditor it work
