### ISSUE TITLE
System module configs

### ISSUE THREAD

**Issue by voltan** [pi-engine/pi#1348]
Hello

I added some needed configs for SEO and optimize <hede> on system module configs , But I think it not good place for them. and we need move this configs to other place, 

I think we can add SEO tab on widget module and manage this settings on them. it need new table for save this settings and add option for generate some new dynamic fields.
what is your idea? 
@taiwen @Marc-pi

**Comment by Marc-pi** [comment]
what new configs? what for? not yet committed?

**Comment by Marc-pi** [comment]
what new configs? what for? not yet committed?
