### ISSUE TITLE
Pi and APC problem on php 5.5 > OPcache

### ISSUE THREAD

**Issue by voltan** [pi-engine/pi#1349]
Hello

On php 5.5+ APC droped and OpCache added, on local host I don't have any problem ( fedora linux + php 5.6 + php-apc package )

But on servers ( cpanel and directadmin control panel and centos ) , after update to php 5.5 I have blank page, 

any change on codes needed for support OpCache?

**Comment by voltan** [comment]
On my test server , I install php 5.5 by OPcache

php info : http://demo.cafeyab.com/info.php

Last version of pi : http://demo.cafeyab.com/pi-develop/www/setup/

**Comment by Marc-pi** [comment]
@voltan 
did you manage to make it work? i want to use OPCache it on my hosting too
@taiwen is there something to change in Pi Core to make it work correctly?

**Comment by Marc-pi** [comment]
@taiwen 
can you check compliance with APC (shipped with PHP - ex ZendCache)?
we would like to run our sites on PHP5.6 > i guess there are not a lot of things to adjust in PHP functions
