### ISSUE TITLE
Not be reached

### ISSUE THREAD

**Issue by txmodxoops** [pi-engine/pi#1355]
the link http://pi-demo.org/ can not be reached

**Comment by Marc-pi** [comment]
yes, thanks, lack of time to manage it
but you can install by your own, the install is super easy : just launch the installer
see https://github.com/Marc-pi/Pi-HowTo/wiki/2-Pi-Install-Upgrade-Run-SSL if you need some help

**Comment by txmodxoops** [comment]
SSL is runned in server I use UwAmp Server for tests but have this error https://github.com/pi-engine/pi/issues/1357 during installation

**Comment by txmodxoops** [comment]
Installation OK - Work fine with php 5.5.15! :+1:
