### ISSUE TITLE
Priorities

### ISSUE THREAD

**Issue by Marc-pi** [pi-engine/pi#1372]
Here the ones i see 
GOALS ==> Improve Speed, fix SEO penality, upgrade for Security and fix bugs

**issue to finish**
- https://github.com/pi-engine/pi/issues/1354 system/sitemap => redirection to kill
- https://github.com/pi-engine/pi/issues/1253 SEO title/slogan setting
- https://github.com/pi-engine/pi/issues/1121 browser caching
- https://github.com/pi-engine/pi/issues/1257 url clickable

**Bugs**
- https://github.com/pi-engine/pi/issues/1364 escaper issue
- https://github.com/pi-engine/pi/issues/1326 search result display (latin characters)
- https://github.com/pi-engine/pi/issues/1334 permission issues
- https://github.com/pi-engine/pi/issues/1333 custom template error msg 

**Improvements**
- https://github.com/pi-engine/pi/issues/1341 kill redirections (login), pagination, search url > SEO penalty
- https://github.com/pi-engine/pi/issues/1335 JS loader js(), bootstrap(), jquery() View Helpers > Async Attribute & add in core lib a JS loader
- https://github.com/pi-engine/pi/issues/1309 update ZF
- https://github.com/pi-engine/pi/issues/1161 captcha is spamed
- https://github.com/pi-engine/pi/issues/936 FB/G+/Twitter connect

**Questions**
- https://github.com/pi-engine/pi/issues/1349 APC cache and PHP5.6

**Comment by Marc-pi** [comment]
I'll take care of CKEditor 4.5 upgrade (should not impact PI integration point), Bootstrap 3.3.5

**Comment by voltan** [comment]
@taiwen , do you have time for work on Pi for 2 or 3 days and ready stable version? than we can use stable version on our projects , we will talk more about next versions

**Comment by Marc-pi** [comment]
+1

**Comment by taiwen** [comment]
Let me check. Perhaps during the coming weekend.

**Comment by Marc-pi** [comment]
ckeditor, FA and Boostrap were upgraded, we improved navigation (there are some workaround to make to fine tine)
@taiwen it's your part now. we need to upgrade ZF since i do run PHP-FPM 2.5.2/2.4.6 are out tonight
please tell us when you are back so we release a stable release asap

**Comment by Marc-pi** [comment]
@taiwen up !! we need fixes for our live sites ! still alive?

**Comment by Marc-pi** [comment]
@taiwen up !

**Comment by Marc-pi** [comment]
@taiwen are U still alive?
