### ISSUE TITLE
comment > answering issues

### ISSUE THREAD

**Issue by Marc-pi** [pi-engine/pi#1382]
- from https://www.yoursite.com/comment/list/index/active/1, you can click on Answer to add your answer, but the displayed blocked is `Comment to answer to xxx` : xxxx is your profile, not the original poster name
- when adding @someoneUsername, you get this url https://www.yourwebsite.com/user/profile/name/someoneUsername, but when you click on the url, it opens your profile, not the someoneUsername profile

**Comment by sta2m** [comment]
> when adding @someoneusername, you get this url https://www.yourwebsite.com/user/profile/name/someoneUsername, but when you click on the url, it opens your profile, not the someoneUsername profile

Je ne reproduis pas ce comportement. Tu es sur que cela fonctionne ou a fonctionné ?

Plus globalement, y a-t-il un intérêt à garder la possibilité de répondre depuis cette page ?

**Comment by sta2m** [comment]
(upd)

**Comment by Marc-pi** [comment]
> when adding @someoneusername
> Ce comportement ne marche pas si on est en mode markdown.

ben là je parle du cas où dans ta réponse tu mets un `@xxxxx` pour citer la personne ou l'interpeller (comme sous GitHub par exemple) : personnellement je le fais souvent, et je vois que sur nextinpact dans les commentaires c'est souvent.
markdown : me souviens plus ce que c'est, si ce n'est que c'est un éditeur simplifié sans bar d'icones.
de mon côté je suis en plein texte : d'ailleurs mon mode est-il approprié?


> Plus globalement, y a-t-il un intérêt à garder la possibilité de répondre depuis cette page ?

tu parles de https://www.yoursite.com/comment/list/index/active/1
à voir en lien avec https://github.com/pi-engine/guide/issues/1179#issuecomment-335599431 (les pages qu'on doit killer)

**Comment by sta2m** [comment]
> from https://www.yoursite.com/comment/list/index/active/1, you can click on Answer to add your answer, but the displayed blocked is Comment to answer to xxx : xxxx is your profile, not the original poster name

Sauf erreur, la page va sauter donc plus d'actu

> when adding @someoneusername, you get this url https://www.yourwebsite.com/user/profile/name/someoneUsername, but when you click on the url, it opens your profile, not the someoneUsername profile

J'ai remonté un peu l'historique, j'ai l'impression que le filtre a été codé mais que rien n'a jamais été fait pour répondre à l'url /profil/name/nomduprofil. C'est corrigé.

**Comment by Marc-pi** [comment]
perfect, a 2years+ bug is fixed :-)
