### ISSUE TITLE
php7 - Session warning

### ISSUE THREAD

**Issue by voltan** [pi-engine/pi#1431]
I have this Session warnings

[warn] #204 in lib/Zend/Session/SessionManager.php
session_write_close(): Session callback expects true/false return value

[warn] #204 in lib/Zend/Session/SessionManager.php
session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/lib/php/session)

**Comment by esprit-dev** [comment]
I've same issue. Any idea ? Seems to be triggered by a wrong session handler call-back (where is it ? does it need a return true / false.
@taiwen

**Comment by Marc-pi** [comment]
@taiwen can you help us on this, it's a tricky issue and important one (deals with security : we need to close properly our sesssions) ===> we need your expertise !

**Comment by Marc-pi** [comment]
see http://stackoverflow.com/questions/34117651/php7-symfony-2-8-failed-to-write-session-data

**Comment by Marc-pi** [comment]
many thanks @esprit-dev , that was a great 5000 commit !
this is fixed @taiwen @voltan

**Comment by voltan** [comment]
thank you very much @esprit-dev
