### ISSUE TITLE
php7 - XssSanitizer error

### ISSUE THREAD

**Issue by voltan** [pi-engine/pi#1434]
[warn] #94 in lib/Pi/Filter/XssSanitizer.php
preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead

**Comment by voltan** [comment]
I plan to use this project for check xss : https://github.com/voku/anti-xss

what is your idea ? @Marc-pi @taiwen

**Comment by taiwen** [comment]
Looks not bad, however I would suggest more investigations since sanitizer is sensitive in many cases in terms of performance.

**Comment by Marc-pi** [comment]
i thought we already had a thirdt part lib for XSS ? the latest is better?

**Comment by voltan** [comment]
we use old method but very useful and fast, it not supported on php 7 , need update it

**Comment by Marc-pi** [comment]
we will test Pi on PHP7 this week with Frederic, we can have a look to adapt code
the question is : is the actual lib outdated technically wise (security filtering methods) ???

**Comment by esprit-dev** [comment]
Fixed

**Comment by voltan** [comment]
thx

**Comment by voltan** [comment]
Still need check

**Comment by Marc-pi** [comment]
yes, it is ok 
see http://php.net/manual/en/migration55.deprecated.php

fix https://github.com/pi-engine/pi/commit/1e336a391860d1a7a10d732ea5270081c008ca0e

**Comment by voltan** [comment]
thx , my changes was OK too?
