### ISSUE TITLE
User > cannot delete a user

### ISSUE THREAD

**Issue by Marc-pi** [pi-engine/pi#1462]
connexion error

one by one or by mass delete (global checkbox with filter unconfirmed account)

**Comment by voltan** [comment]
Here its work

**Comment by Marc-pi** [comment]
here i've still the issue

**Comment by voltan** [comment]
Can you write more information for me? on which page and when its happened?

**Comment by Marc-pi** [comment]
on user module admin (main tab : admin/user/#!/all)
i check the left checkbox, the account is unconfirmed, but i've this error for all accounts even confirmed
is it linked with custom fields?

![image](https://cloud.githubusercontent.com/assets/919332/22688913/8ff0ce8e-ed2e-11e6-8a69-58b3719702fb.png)

**Comment by voltan** [comment]
Let me check tonight

**Comment by Marc-pi** [comment]
ok, thx

**Comment by Marc-pi** [comment]
i still have the issue, and it is very anoying

**Comment by Marc-pi** [comment]
bug confirmed on a newly installed website
cannot manage groups also (same error message)

**Comment by voltan** [comment]
perhaps it happened after remove end of slash , I instaled website a week ago, it work on it

**Comment by Marc-pi** [comment]
Here I installed latest pi code

**Comment by Marc-pi** [comment]
mod security was the culprit
