### ISSUE TITLE
fresh pi install > issue > cannot connect as admin

### ISSUE THREAD

**Issue by Marc-pi** [pi-engine/pi#1486]
cannot connect as admin
r4999

09:20:12.6328
[err] #317 in lib/Zend/Mvc/Router/Http/TreeRouteStack.php
Route with name "user" not found

**Comment by voltan** [comment]
This is first_name field problem on user bar

**Comment by Marc-pi** [comment]
ok,fixed with userbar and check user module is installed, thx
