### ISSUE TITLE
Problem after remove end slash

### ISSUE THREAD

**Issue by voltan** [pi-engine/pi#1524]
Hello

we have some problem after remove end slash, on many of urls we need end of slash, and now some parts of pi not work , for example on system module , role and nav parts

we need fix it

**Comment by Marc-pi** [comment]
yes, declared here https://github.com/pi-engine/guide/issues/825#issuecomment-286401889, will be fixed from April 3rd

**Comment by Marc-pi** [comment]
you can remove in htaccess, we will fix

**Comment by voltan** [comment]
thx
