### ISSUE TITLE
Page module > update error on latest code 

### ISSUE THREAD

**Issue by Marc-pi** [pi-engine/pi#1533]
Echec de la mise à jour.

    db: Echec
        Table alter query failed: SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'title'

**Comment by voltan** [comment]
did you add manually title as key on DB ?

**Comment by Marc-pi** [comment]
No, no change from us

**Comment by esprit-dev** [comment]
@voltan you upgrade check the current version as follow :
if (version_compare($moduleVersion, '1.2.8', '<=')) {

Condition is always true, so update is always replay.
Should be "<" operator ?

Same thing for previous updates (up to 1.2.0)

**Comment by Marc-pi** [comment]
@voltan poke

**Comment by voltan** [comment]
I will check , perhaps it have mistake

**Comment by voltan** [comment]
can you please check it fixed or not?

**Comment by Marc-pi** [comment]
I will in few hours, by no doubt it is the right fix

**Comment by Marc-pi** [comment]
ok
