### ISSUE TITLE
Login by social networks ( hybridauth )

### ISSUE THREAD

**Issue by voltan** [pi-engine/pi#1561]
I add option on Pi core and tools module for login by Google on website. if user had account before he login and if didn't have account, he register first and after that login automatic 

for core changes please see this commit : https://github.com/voltan/pi/commit/f268145dbd292f8455cccadf8c92227fc494fd66

and check tools module : https://github.com/pi-module/tools

demo : https://www.cafeyab.com/tools/oauth

I still need test and and we can all some extra options on it like save log and ...
after test I will move it on user module ( or we can keep it on tools module )

**Comment by Marc-pi** [comment]
good, nice 
Some points : 
* because we need also Twitter and Facebook connectors, why not use a crosss auth lib ???
like the one i was talking https://github.com/pi-engine/pi/issues/936. maybe there is a ZF extension already available.  Or you think it is a better to have our own libs (not too difficult to maintain?)
* i've to merge my pi code to source repo : it ads some improvements for media, but also for user module : passwd quality meter.

**Comment by voltan** [comment]
Hello
Google is for test and ready pi libs, for main version I will add support facebook / twitter and after that instageram / linkedin / github

I will check this zend libe

and can you please send password quality meter on main core?

**Comment by voltan** [comment]
I like https://github.com/hybridauth/hybridauth, I try use it

**Comment by Marc-pi** [comment]
> and can you please send password quality meter on main core?

done

> I like https://github.com/hybridauth/hybridauth, I try use it

don't know if it is the best, but i found it and it seems to be still heavily maintained. 
maybe there is one lib in Zend.

**Comment by voltan** [comment]
I add example login page by hybridauth, at this moment add support for google and twiiter , I will add facebook and github too . this is provider list : https://hybridauth.github.io/providers.html 
any other provider needed?

and after finish test and development we need think about this part poshition? keep on tools module or move it on user module or oauth module?

**Comment by voltan** [comment]
Update hybridauth to RC 1 version https://github.com/hybridauth/hybridauth/releases/tag/v3.0.0-rc.1

**Comment by voltan** [comment]
It added on pi
