### ISSUE TITLE
New pdf system

### ISSUE THREAD

**Issue by voltan** [pi-engine/pi#1571]
Hello
some question about new pdf system : 
1- can you please tell me which fonts are used , `/lib/vendor/tecnickcom/tcpdf/fonts` folder is 27MB, we can clean most of fonts, I will add new font for Persian language
2- ` lib/vendor/autoload.php` and `lib/vendor/composer` needed ? if possible please more it on spipu folder

**Comment by Marc-pi** [comment]
yes, i think we can reduce the font dir : i vote for Google standard font only (Roboto, etc.)

**Comment by voltan** [comment]
Thanks

**Comment by sta2m** [comment]
> 1- can you please tell me which fonts are used , /lib/vendor/tecnickcom/tcpdf/fonts folder is 27MB, we can clean most of fonts, I will add new font for Persian language

By default, it's helvetica. I have removed the others fonts and the examples directory.
We can add other font (like Roboto, etc) in the future if we need.

> 2- lib/vendor/autoload.php and lib/vendor/composer needed ? if possible please more it on spipu folder

HTML2PDF is installed via composer.
We need this files.

**Comment by voltan** [comment]
> By default, it's helvetica. I have removed the others fonts and the examples directory.
We can add other font (like Roboto, etc) in the future if we need.

Thanks, I will add persian font too

> HTML2PDF is installed via composer.
We need this files.

Just can you please move it to spipu folder ? if poshible if not its ok
