### ISSUE TITLE
CKFinder license

### ISSUE THREAD

**Issue by LoneShooter** [pi-engine/pi#165]
Although PI Engine is a free software and uses CKEditor as a WYSIWYG editor, it's file manager plugin, CKFinder, is not free. We should be aware of this.

The authors are clear about licensing the CKFinder - It may be used only for demo purpose without purchasing the license. (http://cksource.com/license/ckfinder)

So, we have the following options:

1) forcing users to upgrade to valid license

2) developing custom file manager plugin

3) using alternative plugins. The only free and open-source solution I found is KCFinder http://kcfinder.sunhater.com/. However, I'm not sure about status of this project (the latest release was in August 25, 2011)

Any other idea?

**Comment by Marc-pi** [comment]
see https://github.com/pi-engine/pi/issues/1314
