### ISSUE TITLE
r1593 - Admin dashboard /  Welcome to Pi Engine block editing bug

### ISSUE THREAD

**Issue by Marc-pi** [pi-engine/pi#446]
editing the block adds a < br > at each edit, and the < br > is displayed. 
Process : add a new text below the Welcom to Pi Engine phrase (here in the example "Mon texte additionnel"). Save. And Edit again to make a slight change , then save. you will see the additional < br > 
![capture2](https://f.cloud.github.com/assets/919332/1415287/e84c8f1c-3ef1-11e3-9095-2c61beb5e5e7.PNG)

**Comment by Marc-pi** [comment]
we have connection error

**Comment by sta2m** [comment]
Marc,

Tu peux me faire une capture du ou des blocs qui posent problème ? 
Tu peux me dire exactement quelles erreurs tu as ? 

Merci

**Comment by sta2m** [comment]
(upd)

**Comment by Marc-pi** [comment]
closed as duplicates
