### ISSUE TITLE
r3068 comment / active comment feature per module  ?

### ISSUE THREAD

**Issue by Marc-pi** [pi-engine/pi#835]
I did not find a way, neither in module settings (article, page) nor in comment module it self , to declare on what module i want to activate the comments.
often on our sites, we need some part with no comments (ex : static corporate page), others that do have comment feature activated (community contents)

**Comment by Marc-pi** [comment]
good, but actually it is only deactivate ( similar to "close Comments"), the comment area is not hidden

![comment](https://cloud.githubusercontent.com/assets/919332/5602175/ee0337d6-933b-11e4-8663-7794cd8b68fd.JPG)

it's good to have such a deactivation, but we need also to set ON/OFF Comment on a module IMHO
I guess it is what Hossein said see https://github.com/pi-engine/pi/issues/1276 
"I think we need option on comment service for active / inactive comment on modules , for example on page module and this option controlled by module config "

**Comment by Marc-pi** [comment]
@taiwen strange, if you deactivate a module, then activate it again, you can not post again in an item that has already comments, only on item that have none comments

**Comment by Marc-pi** [comment]
up !

**Comment by voltan** [comment]
For this version we can manage it on theme very easy , like
```
<?php if (in_array($module, array('news', 'guide'))) {
                            echo Pi::service('comment')->load(array('options' => array('type' => 'js')));
                        } ?>
```

**Comment by Marc-pi** [comment]
Here there is the bug to fix first
