### ISSUE TITLE
module form 

### ISSUE THREAD

**Issue by douzi8** [pi-engine/pi#93]
<ol>
 <li>create src/Form/DemoForm.php
<pre>
namespace Module\{module name}\Form;

use Pi;
use Pi\Form\Form as BaseForm;
use Zend\Form\Form;
use Zend\Form\Element;

class DemoForm extends BaseForm
{
	public function init()
	{
              ....
	}
}
</pre>
 <li> Controller use form
  <pre>
use Module\{module name}\Form\DemoForm;
$form = new DemoForm();
$this->view()->assign(array(
     'form' => $form
 ));
  </pre>
<li> view template echo form
<pre>
echo $this->form()->openTag($form);
$elements = $form->elementList();
foreach ($elements['active'] as $element) {
	echo $this->formRow($element); 
}
$element = $form->get('submit');
echo $this->formElement($element);
$this->form()->closeTag();
</pre>
</ol>
Issues:
<ol>
  <li>How can i custom form html  structor code like bootstrap? As system already support bootstrap css style, how does ZF2 form echo html like bootstrap, can we defined a simple schema so that developer can use it simply, but it best support variety style to fit different design
  <li>if front donot validate form data through javascript ,how does ZF2 validate form element, can do validate in {DemoForm.php}? 
</ol>

**Comment by Marc-pi** [comment]
close as inactive
