### ISSUE TITLE
Update to Respond.js v1.4.0

### ISSUE THREAD

**Issue by krisxoofoo** [pi-engine/pi#951]

**Comment by Marc-pi** [comment]
\www\static\js\respond.js and respond.min.js
@taiwen we run 1.3, 1.4.2 is the latest
https://github.com/scottjehl/Respond/releases

we use also 
* html5_shiv v3.7.0 in \www\static\js\html5shiv.js  (3.7.2 is the latest https://github.com/aFarkas/html5shiv/releases)
* modernizr 2.8.3 www/static/vendor/jquery/extension/modernizr.js (2.8.3 is the latest http://modernizr.com/)

==> i don't know if we really use all of them in our framework to ensure old browser compat
=> no cleanup needed?

**Comment by Marc-pi** [comment]
i just noticed html5_shiv comes with modernizr => we need to replace by compressed versions of these 2 files
